platform :ios, '6.0'

pod 'MagicalRecord', '~> 2.2'

pod 'MBProgressHUD', '~> 0.8'

pod 'Reachability', '~> 3.1.1'

pod 'SSKeychain', '~> 1.2.1'

pod 'APLSlideMenu', '~>0.0.9'

pod 'AFNetworking', '~> 2.2'

pod 'UIKitCategoryAdditions', '~> 0.0.1'

pod 'SDWebImage', '~> 3.5.2'